### ISSUE TITLE
404 when executing `mlflow ui` from mlflow repos root folder

### ISSUE THREAD

**Issue by arinto** [databricks/mlflow#101]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.12.6 (Sierra)
- **MLflow installed from (source or binary)**:  binary
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.2.1
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **npm version (if running the dev UI): N.A
- **Exact command to reproduce**:
  1.  `git clone https://github.com/databricks/mlflow`
  2. `cd mlflow`
  3. `python example/tutorial/train.py` to execute a training
  3. `mlflow ui`
  4.  Open `localhost:5000` in browser

### Describe the problem
Localhost:5000 returns 404. Here's the screenshot:
<img width="413" alt="screen shot 2018-06-29 at 10 26 57 am" src="https://user-images.githubusercontent.com/1780348/42069971-05b1c80c-7b87-11e8-90e7-d7d9712f5d25.png">

In above case, the root folder of code is `/Volume/tvlk-repo/trial/mlflow`, and the `mlruns` folder generated by training execution is in `/Volume/tvlk-repo/trial/mlflow/mlruns`

Interestingly, when I change the other directory and execute `mlflow ui`, I can access the dashboard.
<img width="908" alt="screen shot 2018-06-29 at 10 32 04 am" src="https://user-images.githubusercontent.com/1780348/42070179-c6614a00-7b87-11e8-819f-2906dcf8937a.png">

### Source code / logs
Output from `mlflow ui` in command line:
```
(mlflow-exp) ip-10-10-177-11:mlflow arinto$ mlflow ui
[2018-06-29 10:18:46 +0800] [15782] [INFO] Starting gunicorn 19.8.1
[2018-06-29 10:18:46 +0800] [15782] [INFO] Listening at: http://127.0.0.1:5000 (15782)
[2018-06-29 10:18:46 +0800] [15782] [INFO] Using worker: sync
[2018-06-29 10:18:46 +0800] [15785] [INFO] Booting worker with pid: 15785
[2018-06-29 10:19:27 +0800] [15782] [CRITICAL] WORKER TIMEOUT (pid:15785)
[2018-06-29 10:19:27 +0800] [15785] [INFO] Worker exiting (pid: 15785)
[2018-06-29 10:19:28 +0800] [15794] [INFO] Booting worker with pid: 15794
[2018-06-29 10:27:25 +0800] [15782] [CRITICAL] WORKER TIMEOUT (pid:15794)
[2018-06-29 10:27:25 +0800] [15794] [INFO] Worker exiting (pid: 15794)
[2018-06-29 10:27:25 +0800] [15848] [INFO] Booting worker with pid: 15848
```

**Comment by Genie-Liu** [comment]
I think your issue is the same as #49.

**Comment by mateiz** [comment]
I think it's the same as #108 actually, which is a an issue with Anaconda on Mac OS. The workaround there was to use http://localhost:5000 instead of http://127.0.0.1:5000. Does that fix the issue?

**Comment by arinto** [comment]
Nope, I already reported in the issue that I was using http://localhost:5000.
Here's the `which mlflow` output:
`/Users/arinto/anaconda3/envs/mlflow-exp/bin/mlflow`

I'm using Conda environment in my mlflow installation.

**Comment by arinto** [comment]
I tried to set my *TCP/IP -> IPV6* setting as @dennyglee pointed out, but it still doesn't work. Let me try to restart my laptop.

**Comment by arinto** [comment]
Restarting doesn't help. Will try to install mlflow to system python without anaconda

**Comment by dennyglee** [comment]
Hopefully, that works!  I had originally installed mlflow without Anaconda
(the default macOS Python) and it had worked without issues.

**Comment by arinto** [comment]
Unfortunately it still doesn't work (i.e. using MacOS python3, installed via Homebrew). Here's my config:
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.12.6 (Sierra)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run python -c "from mlflow import version; print(version.VERSION)")**: 0.2.1
- **Python version**: Python 3.6.5
- **which mlflow**: /usr/local/bin/mlflow

Already set my `TCP/IP-IPV6` to LinkLocalOnly
<img width="780" alt="screen shot 2018-07-04 at 3 32 50 pm" src="https://user-images.githubusercontent.com/1780348/42263056-8d047a7c-7f9f-11e8-812a-6764903f099c.png">

**Comment by dennyglee** [comment]
Got it, let me see if I can test a couple of things out @arinto - and to confirm, this is not working for both `http://127.0.0.1:5000` and `http://localhost:5000`?

**Comment by arinto** [comment]
Yes, both urls have the same error

**Comment by Abdul-Rehman-Liaqat** [comment]
So, I was able to run `mlflow ui` command. Here is some information about my system setup:

- I have a default anaconda3 installed. 
- I receive ~/anaconda3/bin/mlflow path  upon executing both `which mlflow` and `which python3.6`
- I also have python2.7 installed which is not through anaconda. `which python2.7` returns me /usr/bin/mlflow .

I copied the mlruns folder to /usr/bin/. Then executed `mlflow ui` command form /usr/bin$ . 
My UI was displayed on both http://localhost:5000/ and http://127.0.0.1:5000/ .

**Comment by Abdul-Rehman-Liaqat** [comment]
True. If mlflow is installed through `pip3 install mlflow` we can the UI at `http://127.0.0.1:5000/`.

**Comment by arinto** [comment]
Interestingly, it works fine with my new project(i.e. a simple Data Science project from scratch).  Probably it was just a glitch.

**Comment by arinto** [comment]
And it works fine with the sample project that I wrote in this issue. 

Here's what I did: 
As far as I remember, `.bash_profile` sets PATH environment variable with 2 Python executables (1 with Anaconda, 1 from with `/Library/Frameworks/....` dir), and I removed the one with `/Library/Frameworks/....`

**Comment by mycaule** [comment]
Found the solution, you have got to change directory first : 
The documentation is unclear.
```
cd example/tutorial/
python train.py
mlflow ui
```

**Comment by smurching** [comment]
Thanks all for the helpful suggestions! Running `mlflow ui` from within a checkout of MLflow runs the dev UI from source, which doesn't come pre-built with the JS/CSS assets needed to render the UI.

We recommend running `mlflow ui` from a directory other than your checkout of MLflow (the same workaround many of you already discussed above), using the `--file-store` option if needed to specify the path to the logging directory to view with the UI. #289 updates the quickstart/tutorial/README to clarify this :).
