### ISSUE TITLE
Bug: display of artifacts in UI doesn't refresh properly

### ISSUE THREAD

**Issue by gsganden** [databricks/mlflow#106]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes, but I don't think that's relevant
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.5
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: 3.6.4
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Bug: the first artifact I click on for a specific run in the UI displays properly, but then that artifact continues to be displayed when I click on other artifacts, until I collapse the "Artifacts" section and re-expand it.

**Comment by mateiz** [comment]
Thanks, I can reproduce this myself.

**Comment by andrewmchen** [comment]
Closed by #115, cheers!
