### ISSUE TITLE
Bar chart for metrics which only have one value

### ISSUE THREAD

**Issue by andrewmchen** [databricks/mlflow#117]
It looks quite silly to display a line chart for metrics which only have one value in it's history. We should consider displaying a bar chart instead.

**Comment by cryptexis** [comment]
@andrewmchen thanks for accepting my solution.  One question though, is it okay that build failed after merging ? :)

**Comment by cryptexis** [comment]
Never mind :)
I have seen it here: https://github.com/databricks/mlflow/commits/master
But as changes are already merged they would be on the master branch during the next one. Sorry  for panicking :))
