### ISSUE TITLE
Cannot connect to ML Flow file for logging 

### ISSUE THREAD

**Issue by andymancodes** [databricks/mlflow#138]
Hi,

I am on windows, Python 3.5 anaconda installation.

I wanted to use Ml flow to log experiements.

When I am trying to use the script:

import os
from mlflow import log_metric, log_param, log_artifact
import mlflow as m

if __name__ == "__main__":

    # Set Tracking URI
    m.set_tracking_uri("file:///C\\Users/hp/Desktop/All.txt")

    # Log a parameter (key-value pair)
    log_param("param1", 5)

    # Log a metric; metrics can be updated throughout the run
    log_metric("foo", 1)
    log_metric("foo", 2)
    log_metric("foo", 3)

    # Log an artifact (output file)
    with open("output.txt", "w") as f:
        f.write("Hello world!")
    log_artifact("output.txt")

I get FileNotFoundError: [WinError 3] The system cannot find the path specified: '/C\\Users\x0hp/Desktop/All.txt'

How do I use it? 

I keep getting file errors like:

Exception: Tracking URI must be a local filesystem URI of the form 'file:///...' or a remote URI of the form 'http://...'. Please update the tracking URI via mlflow.set_tracking_uri

Or

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/C:/Users/hp/Desktop/All.txt'

**Comment by smurching** [comment]
Hi @andymancodes, thanks for bringing this up - lack of good support for logging on Windows is a known issue. Would you be able to try the workarounds in https://github.com/databricks/mlflow/issues/10? Thanks!

**Comment by andymancodes** [comment]
@smurching Thanks!
