### ISSUE TITLE
When comparing results, parameters are incorrectly displayed 

### ISSUE THREAD

**Issue by jeanineharb** [databricks/mlflow#18]
I have executed the example code `example/tutorial/train.py` three times, with three different inputs for `alpha` and `l1_ratio`.
When I select all three runs and compare them, the "Parameters" section shows the values used for the first run, repeated across all three columns.

Input:

| Run | alpha | l1_ratio |
|-------|--------|------------|
| 1 | 2 | 2 |
| 2 | 5 | 1 |
| 3 | 3 | 3 |

Comparison results:
![image](https://user-images.githubusercontent.com/7924513/41111622-c333bc94-6a7c-11e8-9e9c-ff033fddaab0.png)

**Comment by mparkhe** [comment]
Thanks -- this is a great find. We will take a look at it, asap.

**Comment by andrewmchen** [comment]
Should be closed by https://github.com/databricks/mlflow/pull/20.
