### ISSUE TITLE
the command of mlflow cann't set host

### ISSUE THREAD

**Issue by sevenguin** [databricks/mlflow#23]
if i run mlflow ui in my server, then the bind ip will be 127.0.0.1, and i cann't access by my computer. Should the mlflow add the setting of --host, like flask etc.

**Comment by makcedward** [comment]
Believe that, you can try http://localhost:5000

**Comment by aarondav** [comment]
@mdagost has a solution for specifying hosts besides the loopback address in #27!

**Comment by sevenguin** [comment]
@aarondav it's sovled, thanks.
