### ISSUE TITLE
Retrieve experiment ID by name

### ISSUE THREAD

**Issue by mlucas-NU** [databricks/mlflow#34]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Slightly altered version of the tutorial snippet. See below.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
This is a feature request, so it should affect all installations of mlflow 0.1.0.
- **MLflow installed from (source or binary)**: 
`pip3 install mlflow` (version 0.1.0)
- **MLflow version (run ``python -c "from mlflow import version; print(version.version)"``)**:
0.1.0
- **Python version**: 
3.6.2
- **npm version (if running the dev UI):
3.10.8
- **Exact command to reproduce**:
```import mlflow

if __name__ == "__main__":
    # Create Experiment
    exp_id = mlflow.create_experiment('mlucas Test')

    # Start run as a child of that experiment
    mlflow.start_run(experiment_id=exp_id)

    # Log a parameter (key-value pair)
    mlflow.log_param("param1", 5)

    # Log a metric; metrics can be updated throughout the run
    mlflow.log_metric("f1", 0.5)
```

Note that the function I'm requesting doesn't exist. The above code will run once (and create the experiment), but subsequent calls will raise an error because the experiment already exists. There does not appear to be a way to retrieve the experiment ID using the name given the existing mlflow functions.

### Describe the problem
Assuming that I programmatically create experiments, I'd like to be able to programmatically retrieve them as well. Currently, it's very easy to create experiments with `mlflow.create_experiment`, but there does not appear to be a pythonic means of retrieving existing experiment IDs via the module using the experiment name.

To programmatically use an existing experiment by name, I expect either: the create_experiment to return the id of the existing project (less ideal) OR to call something like `get_experiment_by_name` to retrieve experiment metadata OR to have to call list_experiments and find the relevant experiment metadata by looping through the response.

Possible function call: `mlflow.list_experiments()`
Desired response:
>[
>  {
>    "id": 0,
>    "name": "Default",
>    "artifact_location": "/Users/michael.lucas/mlflow/mlruns/0"
>  },
>  ...
>]

Possible function call: `mlflow.get_experiment_by_name(name="mlucas Test")`
Desired response:
>[
>  {
>    "id": 1,
>    "name": "mlucas Test",
>    "artifact_location": "/Users/michael.lucas/mlflow/mlruns/1"
>  }
>]
If no experiments exists, could raise a relevant exception.

Any thoughts on these two options? And if the first is an interesting endpoint in general, does the proposed response (JSON-ic list of dicts) make sense within the mlflow paradigm?

Thanks!
Michael

**Comment by mlucas-NU** [comment]
Closing issue after merge. Thanks @mparkhe!

**Comment by yinxiEquinor** [comment]
Hi All,

I am wondering how to list all the experiments created with a given artifact path?

I am running in DataBricks 

```
from  mlflow.tracking import MlflowClient
client = MlflowClient()
experiments = client.list_experiments() # returns a list of mlflow.entities.Experiment
```
this returns all the experiments under the default databricks folder 'dbfs:/databricks/mlflow/'

however, i want to retrieve an experiment created as :
`mlflow.create_experiment(EXPERIMENT_NAME, artifact_location="dbfs:/mnt/<path_to_file>")`

how do i get the experiment_id and start runs for this experiment?

Thanks!
Y
