### ISSUE TITLE
mlflow ui - Compare Selected Parameters Issue

### ISSUE THREAD

**Issue by virajpai** [databricks/mlflow#41]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 4.14.47-1-MANJARO
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: Python 3.6.5 :: Anaconda custom (64-bit)
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
I ran example/tutorial/train.py as described in the tutorials multiple times with different combinations of parameters. Then I launched mlflow ui and was playing around with it. When I select multiple Runs and click on Compare Selected, I am getting same Parameters across the runs though they are different on the previous screen.
![mlflow_ui](https://user-images.githubusercontent.com/16618851/41330768-fc53bfa4-6ef2-11e8-9792-25c20b813c6b.png)

**Comment by jeanineharb** [comment]
This issue was addressed in #20.
