### ISSUE TITLE
Metrics chart wrongly connects points on X axis

### ISSUE THREAD

**Issue by zegerhoogeboom** [databricks/mlflow#45]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: 3.6.5
- **npm version (if running the dev UI)**: 6.0.1
- **Exact command to reproduce**: NA

### Describe the problem
In the UI at the metrics graph view, it looks like this for me:
![image](https://user-images.githubusercontent.com/5371096/41408703-dc1d732e-6fd3-11e8-968f-f18192b908db.png)

The data points are logged at the end of an epoch using this Keras callback:
```
class LossHistory(Callback):
    def on_epoch_end(self, epoch, logs=None):
        log_metric("loss", logs.get('loss'))
        # in reality more metrics here
```
`logs.get('loss')` just returns a number. The connections of the dots in the interface should be connecting X=0 to X=1 to X=2 and so on. Why they are currently connected in this strange way, I have no clue.

**Comment by mateiz** [comment]
Is there any chance you could share your MLflow run folder that caused this (`mlruns/0/<runID>`) or the file for the metric inside there? Also, which browser are you using?

**Comment by zegerhoogeboom** [comment]
Terribly sorry for the late reply. `cat mlruns/0/2924aa6b449944bc849d4381e0fa3570/metrics/loss`:

```
0 4.54306590325
0 3.50579357207
0 3.63842143944
0 3.63074730358
0 3.62895112526
0 3.60019535707
0 3.34938469377
0 3.69437173072
0 3.4442458695
0 5.05011896209
```

`cat mlruns/0/2924aa6b449944bc849d4381e0fa3570/meta.yml`:
```
artifact_uri: /app/mlruns/0/2924aa6b449944bc849d4381e0fa3570/artifacts
end_time: null
entry_point_name: !!python/unicode ''
experiment_id: !!python/long '0'
name: Run 5
run_uuid: 2924aa6b449944bc849d4381e0fa3570
source_name: !!python/unicode '/home/{my source code location}.py'
source_type: 4
source_version: !!python/unicode '94de7c2a7562525db2ead17fe8d020a7ca1cf32a'
start_time: !!python/long '1529310274917'
status: 1
tags: []
user_id: !!python/unicode '{my user name}'
```

It's being run from a Docker container using `continuumio/miniconda`, the host is running CentOS 7. I'm using Chrome (version 67) as my browser.

**Comment by mateiz** [comment]
Interesting, I don't see this on Chrome 67 with the same file. Do you have any extensions that might be blocking JavaScript? It's also a bit weird that your metrics are being logged with 0 as the timestamp (it should be the time since the epoch), but I tried it with either 0 or a recent timestamp and it seems to work OK.
