### ISSUE TITLE
[UI] Comparing Runs Parameters are wrong in comparison screen

### ISSUE THREAD

**Issue by whitewizard333** [databricks/mlflow#48]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 (64 bit)
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: 3.6
- **npm version (if running the dev UI): NA
- **Exact command to reproduce**:
Go to path mlflow\example\tutorial
1) python train.py 
2) python train.py 0.4 0.3

3) Select both run summary check box 
![image](https://user-images.githubusercontent.com/25137194/41429035-7f3db406-7029-11e8-9f83-61e5f33d59b4.png)
4) Click Compare Selected runs
5) Parameters (alpha, l1_ratio) are showing same (0.5 0.5) for both run. It should have been (0.4 0.3) for the second run
![image](https://user-images.githubusercontent.com/25137194/41429196-07ae7c1c-702a-11e8-8190-1b8f87519ecd.png)

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.
Compare results window is showing last checked run parameters for both the runs. (Refer Images attached)
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

NA

Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Same as "Exact command to reproduce section" above (Follow steps 1 to 5)

**Comment by mparkhe** [comment]
Hi @whitewizard333 : Thanks for the note. This is the same as issue #18 and has been fixed by PR #20 on June 7, 2018.

We are looking to make a new library release. If the mean time, checking out repo from github to the latest should address this issues.

**Comment by whitewizard333** [comment]
Thanks @mparkhe 
closing it.
