### ISSUE TITLE
mlflow run local project will fetch project from git

### ISSUE THREAD

**Issue by zxsimple** [databricks/mlflow#5]
Following the example to run project with
`mlflow run example/tutorial -P alpha=0.4`

Got the following error:
> cmdline: git remote add origin d:/Workspace/mlflow/example/tutorial
stderr: 'fatal: remote origin already exists.'

How to execute the local project?

**Comment by mateiz** [comment]
This is an issue on Windows only right now. We're not supporting Windows in this first release, so we'd recommend using a Docker container with Linux, or trying Bash-on-Windows (Windows Subsystem for Linux).

**Comment by zxsimple** [comment]
Got it. I'll build docker image for testing. Thanks!

**Comment by aarondav** [comment]
Closing in favor of #10 to track the Windows-related issues.
