### ISSUE TITLE
Compare Runs:  the parameter appear to be same

### ISSUE THREAD

**Issue by Genie-Liu** [databricks/mlflow#57]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: 0.1.0
- **Python version**: python 3.6.5
- **npm version (if running the dev UI): 
- **Exact command to reproduce**: 

### Describe the problem
After selecting multi result to compare, the parameter part appear to be all the same.

**Comment by mateiz** [comment]
Thanks for the report; this has been fixed in master and should be out in the next release.
