### ISSUE TITLE
Not able to access tracking UI when installing from source

### ISSUE THREAD

**Issue by wegamekinglc** [databricks/mlflow#75]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **MLflow installed from (source or binary)**:  Source
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**: commit 80db6e5
- **Python version**:  3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**: mflow ui

### Describe the problem
I just do `python setup.py install` under the source directory and then run `mlflow ui`. However when I tried to access `http://localhost:5000`, I always got 404 error. 

### Source code / logs

```
cd mlflow
python setup.py install
cd ../..
mlflow ui
```

**Comment by jeanineharb** [comment]
You should also generate the necessary files for the frontend, as described in [CONTRIBUTING.rst](https://github.com/databricks/mlflow/blob/master/CONTRIBUTING.rst).
