### ISSUE TITLE
Compiling  service.proto

### ISSUE THREAD

**Issue by cryptexis** [databricks/mlflow#77]
Hi,
currently I am trying to implement a functionality for getting an experiment by name for RestStore object. I figured that some work should be done in protobuf files. However, when I try to compile service.proto  I get the following error:

```
scalapb/scalapb.proto: File not found.
databricks.proto: File not found.
service.proto: Import "scalapb/scalapb.proto" was not found or had errors.
service.proto: Import "databricks.proto" was not found or had errors.
```
Is there a specific reason why those 2 files are missing? 

Thanks in advance :)

**Comment by andrewmchen** [comment]
Currently we build our protobuf source in Databrick's monorepo to take advantage of some custom protobuf extensions. I'm working on seeing if we can open source these two files. We should get an answer within a week.

**Comment by andrewmchen** [comment]
Should be fixed by https://github.com/databricks/mlflow/pull/74.
